# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        7,
        _('Departments'),
        ['lineasDepto'],
        [],
[
    (_('Tumbes'), _('Is northwest')),
    (_('Loreto'), _('Is north')),
    (_('Piura'), _('Is northwest')),
    (_('Amazonas'), _('Is northwest')),
    (_('Cajamarca'), _('Is northwest')),
    (_('Lambayeque'), _('Is northwest')),
    (_('San Martín'), _('Is north')),
    (_('La Libertad'), _('Is northwest')),
    (_('Ancash'), _('Is west')),
    (_('Huanuco'), _('Is in the center')),
    (_('Lima'), _('Is southwest')),
    (_('Cerro de Pasco'), _('Is in the center')),
    (_('Junín'), _('Is south')),
    (_('Ucayali'), _('Is east')),
    (_('Madre de Dios'), _('Is southeast')),
    (_('Cuzco'), _('Is southeast')),
    (_('Ica'), _('Is south')),
    (_('Huancavelica'), _('Is south')),
    (_('Ayacucho'), _('Is south')),
    (_('Arequipa'), _('Is southeast')),
    (_('Apurimac'), _('Is southeast')),
    (_('Puno'), _('Is southeast')),
    (_('Moquegua'), _('Is southeast')),
    (_('Tacna'), _('Is southeast'))
]
]

LEVEL2 = [
        2,
        _('Departmental capitals'),
        ['lineasDepto', 'capitales'],
        [],
[
    (_('Lima'), _('Is southwest')),
    (_('Abancay'), _('Is southeast')),
    (_('Arequipa'), _('Is southeast')),
    (_('Ayacucho'), _('Is south')),
    (_('Cajamarca'), _('Is northwest')),
    (_('Callao'), _('Is southwest')),
    (_('Cerro de Pasco'), _('Is in the center')),
    (_('Chachapoyas'), _('Is northwest')),
    (_('Chiclayo'), _('Is northwest')),
    (_('Cusco'), _('Is southeast')),
    (_('Huánuco'), _('Is in the center')),
    (_('Huancavelica'), _('Is south')),
    (_('Huancayo'), _('Is south')),
    (_('Huaraz'), _('Is west')),
    (_('Ica'), _('Is south')),
    (_('Iquitos'), _('Is northeast')),
    (_('Moquegua'), _('Is southeast')),
    (_('Moyobamba'), _('Is north')),
    (_('Piura'), _('Is northwest')),
    (_('Pucallpa'), _('Is north')),
    (_('Puerto Maldonado'), _('Is southeast')),
    (_('Puno'), _('Is southeast')),
    (_('Tacna'), _('Is southeast')),
    (_('Trujillo'), _('Is northwest')),
    (_('Tumbes'), _('Is northwest'))
]
]

LEVEL3 = [
        2,
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (_('Lima'), _('Is southwest')),
    (_('Abancay'), _('Is southeast')),
    (_('Arequipa'), _('Is southeast')),
    (_('Ayacucho'), _('Is south')),
    (_('Cajamarca'), _('Is northwest')),
    (_('Callao'), _('Is southwest')),
    (_('Cerro de Pasco'), _('Is in the center')),
    (_('Chachapoyas'), _('Is northwest')),
    (_('Chiclayo'), _('Is northwest')),
    (_('Cusco'), _('Is southeast')),
    (_('Huánuco'), _('Is in the center')),
    (_('Huancavelica'), _('Is south')),
    (_('Huancayo'), _('Is south')),
    (_('Huaraz'), _('Is west')),
    (_('Ica'), _('Is south')),
    (_('Iquitos'), _('Is northeast')),
    (_('Moquegua'), _('Is southeast')),
    (_('Moyobamba'), _('Is north')),
    (_('Piura'), _('Is northwest')),
    (_('Pucallpa'), _('Is north')),
    (_('Puerto Maldonado'), _('Is southeast')),
    (_('Puno'), _('Is southeast')),
    (_('Tacna'), _('Is southeast')),
    (_('Trujillo'), _('Is northwest')),
    (_('Tumbes'), _('Is northwest')),
    (_('Azángaro'), _('Is southeast')),
    (_('Bagua'), _('Is northwest')),
    (_('Barranca'), _('Is west')),
    (_('Caballococha'), _('Is northeast')),
    (_('Camana'), _('Is south')),
    (_('Caraveli'), _('Is south')),
    (_('Casma'), _('Is west')),
    (_('Chimbote'), _('Is west')),
    (_('Chincha Alta'), _('Is south')),
    (_('Contamana'), _('Is north')),
    (_('Coracora'), _('Is south')),
    (_('Cotahuasi'), _('Is south')),
    (_('Flor de Agosto'), _('Is northeast')),
    (_('Huacho'), _('Is west')),
    (_('Huarmey'), _('Is west')),
    (_('Iñapari'), _('Is east')),
    (_('Juliaca'), _('Is southeast')),
    (_('La Oroya'), _('Is in the center')),
    (_('Macusani'), _('Is southeast')),
    (_('Manú'), _('Is east')),
    (_('Mollendo'), _('Is southeast')),
    (_('Nauta'), _('Is northeast')),
    (_('Nazca'), _('Is south')),
    (_('Palpa'), _('Is south')),
    (_('Pisco'), _('Is south')),
    (_('Puerto Inca'), _('Is in the center')),
    (_('Requena'), _('Is northeast')),
    (_('San Pedro de Lloc'), _('Is northwest')),
    (_('San Vicente de Cañete'), _('Is southwest')),
    (_('Sullana'), _('Is northwest')),
    (_('Talara'), _('Is northwest')),
    (_('Tarapoto'), _('Is north')),
    (_('Tingo Maria'), _('Is in the center'))
]
]

LEVEL4 = [
        4,
        _('Waterways'),
        ['lineasDepto', 'rios'],
        [],
[
    (_('Napo River'), _('Is north')),
    (_('Curaray River'), _('Is north')),
    (_('Tigre River'), _('Is north')),
    (_('Corrientes River'), _('Is north')),
    (_('Pastaza River'), _('Is north')),
    (_('Amazonas River'), _('Is northeast')),
    (_('Javari River'), _('Is northeast')),
    (_('Juruá River'), _('Is east')),
    (_('Acre River'), _('Is east')),
    (_('Iaco River'), _('Is east')),
    (_('Alto Purús River'), _('Is east')),
    (_('Madre de Dios River'), _('Is northeast')),
    (_('Piedras River'), _('Is northeast')),
    (_('Inambari River'), _('Is southeast')),
    (_('Putumayo River'), _('Is northeast')),
    (_('Marañón River'), _('Is northwest')),
    (_('Santiago River'), _('Is northwest')),
    (_('Huallaga River'), _('Is in the center')),
    (_('Ucayali River'), _('Is in the center')),
    (_('Urubamba River'), _('Is southeast')),
    (_('Tambo River'), _('Is southeast')),
    (_('Apurimac River'), _('Is southeast')),
    (_('Lake Titicaca'), _('Is southeast')),
    (_('Gulf of Guayaquil'), _('Is northwest')),
    (_('Sechura Bay'), _('Is northwest')),
    (_('Pacific Ocean'), _('Is west'))
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3, LEVEL4]

